### ISSUE TITLE
Gives success message but throws error and does not generate an ouput video.

### ISSUE THREAD

**Issue by o0oradaro0o** [nicolai256/Few-Shot-Patch-Based-Training#2]
Hi there, cool tool, good setup guide. can't quite get it working. It spits out the train\input_filtered and seems happy with what i put into output but then when it shows the success popup there is an error in the ui window and i cannot find any output video.

I will admit i installed newer versions of a few of the pip installs so this could be on me, but i am using the listed tensorflow and torch versions which seem the be the bits throwing this error. 

here are the last few log lines:
```

2022-10-31 21:31:01.339784: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-31 21:31:01.738367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7435 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:0a:00.0, compute capability: 8.6
C:\Users\Admin\miniconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
{'type': 'DatasetPatches_M', 'dir_pre': 'X:\\Few-Shot-Patch-Based-Training/logs\\testing_train/input_filtered', 'dir_post': 'X:\\Few-Shot-Patch-Based-Training/logs\\testing_train/output', 'dir_mask': 'X:\\Few-Shot-Patch-Based-Training/logs\\testing_train/mask', 'patch_size': 32, 'device': 'cuda:0', 'dir_x1': None, 'dir_x2': None, 'dir_x3': None, 'dir_x4': None, 'dir_x5': None, 'dir_x6': None, 'dir_x7': None, 'dir_x8': None, 'dir_x9': None}
Traceback (most recent call last):
  File "X:\Few-Shot-Patch-Based-Training\train.py", line 231, in <module>
    trainer.train(generator, discriminator, int(config['trainer']['epochs']), data_root, args_config, 0)
  File "X:\Few-Shot-Patch-Based-Training\trainers.py", line 153, in train
    self.test_on_full_image(generator, batch_num, data_root, config_yaml_name)
  File "X:\Few-Shot-Patch-Based-Training\trainers.py", line 215, in test_on_full_image
    0, 0, 0, 0, 0, generator(batch['pre'])
  File "C:\Users\Admin\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "X:\Few-Shot-Patch-Based-Training\models.py", line 122, in forward
    output = self.upconv1(torch.cat((output, output_1), dim=1))
RuntimeError: Sizes of tensors must match except in dimension 2. Got 241 and 242 (The offending index is 0)
```

**Comment by IzumiSatoshi** [comment]
Hello.
Someone else had the same error as you. source : [https://twitter.com/Mega_Gorilla_/status/1589277833456943105](url)  
According to that person, setting the image size to multiple of 256 seems to have solved the problem.
Also, make sure that the image size in inputfiltered is the same as the image size you put in output.
Hopefully this information will be helpful to you.

**Comment by o0oradaro0o** [comment]
@IzumiSatoshi Thank you so much! this completely fixed the issue! So happy I can use this now!
